import { Bell, FileUp, Landmark, Menu, MessageCircle, Wallet } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Logo } from '../components/Common/Logo'
import { ProgressBar } from '../components/Common/ProgressBar'
import { formatCurrency } from '../lib/format'

const menu = [
  { key: 'home', label: 'Главная', icon: Landmark },
  { key: 'documents', label: 'Документы', icon: FileUp },
  { key: 'finance', label: 'Финансы', icon: Wallet },
  { key: 'events', label: 'События', icon: Bell },
  { key: 'chat', label: 'Чат с юристом', icon: MessageCircle },
] as const
type Section = typeof menu[number]['key']

const contractTotal = 180_000
const paid = 116_000
const remaining = contractTotal - paid
const progress = Math.round((paid / contractTotal) * 100)

export function DemoCabinet() {
  const [section, setSection] = useState<Section>('home')
  const [mobileMenu, setMobileMenu] = useState(false)
  return <div className="min-h-screen bg-[#f7f9fc] text-navy-800"><aside className={`fixed inset-y-0 left-0 z-30 flex w-64 flex-col bg-navy-800 p-4 text-white transition-transform lg:translate-x-0 ${mobileMenu ? 'translate-x-0' : '-translate-x-full'}`}><Logo onDark /><p className="mt-6 rounded-xl bg-gold-400/15 px-3 py-2 text-xs text-gold-200">Демо-кабинет · данные вымышлены</p><nav className="mt-5 space-y-1">{menu.map((item) => { const Icon = item.icon; return <button key={item.key} onClick={() => { setSection(item.key); setMobileMenu(false) }} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-medium ${section === item.key ? 'bg-white/12 text-white' : 'text-white/65 hover:bg-white/5'}`}><Icon className="h-5 w-5 text-gold-300" />{item.label}</button> })}</nav><div className="mt-auto border-t border-white/10 pt-4"><p className="text-sm font-semibold">Максим Андреевич Соколов</p><p className="mt-1 text-xs text-white/50">Демонстрационный клиент</p><Link to="/login" className="mt-4 inline-flex text-sm text-gold-300 hover:text-gold-200">Вернуться ко входу</Link></div></aside>{mobileMenu && <button aria-label="Закрыть меню" onClick={() => setMobileMenu(false)} className="fixed inset-0 z-20 bg-navy-950/50 lg:hidden" />}<div className="min-h-screen lg:pl-64"><header className="sticky top-0 z-10 flex h-16 items-center gap-3 border-b border-navy-100 bg-white/90 px-4 backdrop-blur sm:px-6"><button onClick={() => setMobileMenu(true)} className="rounded-xl p-2 text-navy-600 lg:hidden"><Menu className="h-5 w-5" /></button><div><p className="text-xs text-navy-400">Демо-версия личного кабинета</p><h1 className="font-bold">{menu.find((item) => item.key === section)?.label}</h1></div></header><main className="mx-auto max-w-5xl p-4 pb-24 sm:p-6">{section === 'home' && <DemoHome go={setSection} />}{section === 'documents' && <DemoDocuments />}{section === 'finance' && <DemoFinance />}{section === 'events' && <DemoEvents />}{section === 'chat' && <DemoChat />}</main></div></div>
}

function DemoHome({ go }: { go: (section: Section) => void }) { return <div className="space-y-5"><section className="rounded-2xl bg-gradient-to-br from-navy-800 to-navy-950 p-5 text-white shadow-card sm:p-7"><p className="text-sm text-gold-300">✦ Коротко о вашем деле</p><p className="mt-3 text-xs text-white/60">Сегодня, 19 июля 2026</p><h2 className="mt-1 text-2xl font-bold">Здравствуйте, Максим Андреевич!</h2><div className="mt-5 rounded-xl border border-emerald-300/30 bg-emerald-400/10 p-4"><p className="font-bold">Делом занимаются юристы</p><p className="mt-1 text-sm leading-5 text-white/75">Документы получены и проверяются. С вашей стороны сейчас ничего не требуется — мы сообщим о следующем шаге.</p></div><div className="mt-5 grid grid-cols-5 gap-2">{['Знакомство', 'Документы', 'Подача', 'Процедура', 'Завершение'].map((label, index) => <div key={label} className={`rounded-xl border p-2 text-center text-[10px] sm:text-xs ${index === 1 ? 'border-gold-300 bg-white/15' : index < 1 ? 'border-emerald-300/40 bg-emerald-400/10' : 'border-white/10 bg-white/5'}`}><span className="mx-auto grid h-6 w-6 place-items-center rounded-full bg-gold-400 text-xs font-bold text-navy-900">{index < 1 ? '✓' : index + 1}</span><p className="mt-2 hidden sm:block">{label}</p></div>)}</div><p className="mt-3 text-center text-xs text-white/60">Этап 2 из 5 · Подготовка документов</p></section><div className="grid gap-4 sm:grid-cols-2"><button onClick={() => go('documents')} className="card p-5 text-left card-hover"><FileUp className="h-6 w-6 text-gold-600" /><h3 className="mt-3 font-bold">Документы</h3><p className="mt-1 text-sm text-navy-500">2 документа ожидают загрузки</p></button><button onClick={() => go('finance')} className="card p-5 text-left card-hover"><Wallet className="h-6 w-6 text-gold-600" /><h3 className="mt-3 font-bold">Оплата по договору</h3><p className="mt-1 text-sm text-navy-500">Остаток: {formatCurrency(remaining)}</p></button></div></div> }

function DemoFinance() { return <div className="space-y-5"><section className="card overflow-hidden"><div className="bg-gradient-to-br from-navy-800 to-navy-950 p-5 text-white"><p className="flex items-center gap-2 text-sm text-gold-300"><Wallet className="h-4 w-4" /> Ваш договор с компанией</p><h2 className="mt-2 text-xl font-bold">Юридическое сопровождение процедуры</h2><p className="mt-2 text-sm text-white/70">Договор № ДЕМО-2026/47 · от 14.07.2026</p></div><div className="grid gap-4 p-5 sm:grid-cols-3"><DemoAmount label="Стоимость договора" value={contractTotal} hint="Оплата по графику" /><DemoAmount label="Уже оплачено" value={paid} hint="Первый платёж и 2 платежа" green /><DemoAmount label="Осталось оплатить" value={remaining} hint="8 платежей по графику" /></div></section><section className="card p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><h3 className="font-bold">Прогресс оплаты</h3><p className="mt-1 text-sm text-navy-500">Оплата услуг по договору</p></div><span className="text-3xl font-bold text-gold-600">{progress}%</span></div><ProgressBar value={progress} className="mt-5" /><div className="mt-3 flex justify-between text-sm text-navy-500"><span>Внесено: {formatCurrency(paid)}</span><span>Осталось: {formatCurrency(remaining)}</span></div></section><section className="card overflow-hidden"><div className="border-b border-navy-100 p-5"><h3 className="font-bold">График платежей</h3><p className="mt-1 text-sm text-navy-500">Следующий платёж — 14 августа 2026</p></div><div className="divide-y divide-navy-100">{[['14.07.2026', 'Первый платёж', 100_000, 'Оплачен'], ['14.08.2026', 'Ежемесячный платёж № 1', 8_000, 'Ожидается'], ['14.09.2026', 'Ежемесячный платёж № 2', 8_000, 'Ожидается']].map(([date, label, amount, status]) => <div key={String(date)} className="flex items-center justify-between gap-3 p-4"><div><p className="font-medium">{label}</p><p className="text-xs text-navy-400">{date}</p></div><div className="text-right"><p className="font-bold">{formatCurrency(Number(amount))}</p><span className={`text-xs font-medium ${status === 'Оплачен' ? 'text-emerald-600' : 'text-gold-600'}`}>{status}</span></div></div>)}</div></section><section className="rounded-2xl border border-gold-200 bg-gold-50 p-5"><p className="font-semibold">Дополнительные расходы</p><p className="mt-1 text-sm leading-6 text-navy-600">Обязательные платежи по процедуре — например, депозит суда, госпошлина или нотариальная доверенность — не входят в стоимость сопровождения. Юрист заранее объяснит, если потребуется оплата.</p></section></div> }

function DemoAmount({ label, value, hint, green = false }: { label: string; value: number; hint: string; green?: boolean }) { return <div className="rounded-xl bg-navy-50 p-4"><p className="text-xs uppercase tracking-wide text-navy-400">{label}</p><p className={`mt-2 text-xl font-bold ${green ? 'text-emerald-600' : 'text-navy-800'}`}>{formatCurrency(value)}</p><p className="mt-1 text-xs text-navy-500">{hint}</p></div> }
function DemoDocuments() { return <div className="space-y-3"><h2 className="text-xl font-bold">Документы для загрузки</h2><p className="text-sm text-navy-500">В демо показан персональный список документов. В настоящем кабинете он формируется юристом.</p>{['Паспорт гражданина РФ', 'Справка о доходах'].map((item) => <div key={item} className="card flex items-center justify-between gap-3 p-5"><div><h3 className="font-semibold">{item}</h3><p className="mt-1 text-sm text-navy-500">Загрузите фото или PDF — юрист проверит файл.</p></div><span className="chip bg-gold-100 text-gold-700">Нужно загрузить</span></div>)}</div> }
function DemoEvents() { return <div className="space-y-3"><h2 className="text-xl font-bold">События по делу</h2>{['Юрист начал проверку документов', 'Подписанный договор добавлен в архив', 'Следующий этап: подготовка заявления'].map((item, index) => <div key={item} className="card flex gap-3 p-5"><Bell className="h-5 w-5 shrink-0 text-gold-600" /><div><p className="font-semibold">{item}</p><p className="mt-1 text-sm text-navy-500">Демонстрационное событие · {index + 1} день назад</p></div></div>)}</div> }
function DemoChat() { return <div className="card p-5"><h2 className="flex items-center gap-2 text-xl font-bold"><MessageCircle className="h-5 w-5 text-gold-600" />Чат с юристом</h2><div className="mt-5 space-y-3 rounded-xl bg-navy-50 p-4"><div className="max-w-[85%] rounded-2xl rounded-bl-md bg-white p-3 text-sm shadow-sm">Здравствуйте! Мы получили договор и начинаем проверку документов.</div><div className="ml-auto max-w-[85%] rounded-2xl rounded-br-md bg-navy-800 p-3 text-sm text-white">Спасибо, понял.</div></div><button className="btn-primary mt-4" disabled>В демо-версии чат недоступен</button></div> }
